### ISSUE TITLE
Messy markup

### ISSUE THREAD

**Issue by jibiel** [sergio-fry/Simple-nicEdit#4]
Seems like Simple-nicEdit generates pretty ugly markup when you edit stuff in the «visual editor».
Assume I'd like to input this strings:

`Lorem ipsum dolor sit amet,
consectetur adipiscing elit.
Pellentesque laoreet.`,

taping return to set new line. Then in the «Edit HTML» section it'll be

``` html
Lorem ipsum dolor sit amet,<div>consectetur adipiscing elit.</div><div>Pellentesque laoreet.</div>
```

Things will go even worse if we'll try to add blank line like this:
`Lorem ipsum dolor sit amet,
consectetur adipiscing elit.`

`Pellentesque laoreet.`,

``` html
Lorem ipsum dolor sit amet,<div>consectetur adipiscing elit.</div><div><br></div><div>Pellentesque laoreet.</div>
```

And so on..
I heard this kind of job is for `<p></p>` and `<br />` buddies. May we fix Simple-nicEdit core in this repository?

**Comment by sergio-fry** [comment]
You are right! But I think, that we could fork one of repos:
- https://github.com/danishkhan/NicEdit
- https://github.com/i5m/NicEdit

**Comment by jibiel** [comment]
Unfortunately their nicEdit.js have the same issue too. Just checked it.
Think I'll just duplicate this post in the first repo.

**Comment by sergio-fry** [comment]
I think that it should be a separated git repo. You could fork one of existing or create your own. And after fixing we could add submodule to SimpleNicedit.

Good Luck!

**Comment by jibiel** [comment]
Please accept my [apologies](https://twitter.com/tpope/status/654703831360532488).
